nytimes/gziphandler

gzip.go
gzip_test.go

Responses should acknowledge Accept-Encoding - https://www.maxcdn.com/blog/accept-encoding-its-vary-important/

Use standard Vary response header

---

gzip.go

When using: 
```go
defer gzw.Close()
```
The gzip.Writer was being closed **after** being put back into the pool of writers.
As per: https://golang.org/pkg/compress/gzip/#Writer.Close, calling Close flushes any unwritten data to the underlying io.Writer. This should happen before being placed back into the pool to be used by another connection.

Close gzip Writer before putting back into pool

---

README.md

Although it does not matter for go if you do `go get github.com/NYTimes/gziphandler` or `go get github.com/nytimesimes/gziphandler` you might end up with two copies of your library in your $GOPATH depending where you copy the package path from. (example from README or browser url)

Case sensitive package name in example

---

gzip.go

When there is something to close, use deferred functions.
Otherwise, in this case, the Gzip writer will never be closed nor put back in the pool if a downstream handler panics.
Of course, we still close the writer **before** putting it back in the pool as deferred function calls are LIFO executed.
Also, `DEFAULT_QVALUE` should be changed to `DefaultQvalue` and `e := make([]string, 0)` to `var e []string`.

Use deferred Gzip closing

---

gzip.go
gzip_test.go

When using the `net/http` server, if the "Content-Type" header of the response is not set at the time that it the response is served the `http` package will [automatically try to sniff the content type](https://golang.org/pkg/net/http/#ServeContent). When using `gziphandler`, if the response is gzip compressed it will set the `Content-Type` of the response to be `application/x-gzip`.
This can be surprising for developers that rely on the behavior of `ServeContent` to apply the correct `Content-Type` header. Having an incorrect content-type header can cause unexpected behavior, depending on the browser.
Ideally the wrapped handler should set the `Content-Type` before returning, but since the standard library automatically handles this I thought it would be a good idea to have the same …

Automatically infer content type of response

---

gzip.go
gzip_test.go

This change allows the body to be completely empty, that means without
gzip headers. This a requirement with status codes that do not allow
for a body, for example 204 No Content.
It also changes to a lazily initialise method for the gzip writer.
Fixes #5.

Allow body to be empty

---

gzip.go
gzip_test.go

This removes the need to calculate the index on every request.

Use gzipWriterPools index rather then gzip level in GzipResponseWriter

---

gzip.go

Remove extraneous "p" in comment.

gziphandler: fix typo in comment

---

.travis.yml
gzip.go
gzip_test.go

This make possible to skip compression if the response is smaller than the specified size.

Add support to skiping gzip for small responses. Fixes #24

---

.travis.yml
gzip.go
gzip_test.go

Reverts NYTimes/gziphandler#30

Revert "Add support to skiping gzip for small responses. Fixes #24"

---

gzip.go
gzip_test.go

If the handler is already closed, then closing it again causes the gzip writer to be in the pool twice and to be closed in the middle of potentially another write.

Unset gw once closed

---

.travis.yml
gzip_go18.go
gzip_go18_test.go

add support for H2 Push without removing support for previous Go versions.
#28

support for H2 Push

---

.travis.yml
gzip.go
gzip_test.go

- go 1.8
- Linux 64
- I using the package with templates
- I expect to see the template as it should :smiley:
- But I get the template with some special chars. It looks like bad decoding
The problem comes from the size limitation.
If the template package is used, it can calls Write multiple times with variable length.
In any case the response writer must be the same for the all response inside the same request. So the package as is, is not good.
I made some modifications to prevent using different response writers on successive calls.
But the size limitation become pretty pointless with template or other handlers calling multiple times the Write function.

Minimum size not compatible with template package

---

gzip.go
gzip_test.go

The HttpStatus was getting lost - every response was a 200 OK because ResponseWriter.WriteHeader() was never called.

Set the HttpStatus correctly in the response header

---

gzip.go
gzip_test.go

When gzip is used as middleware in a `parent -> gzip -> inner` setup, sometimes the parent handler wants to call `ResponseWriter.WriteHeader` knowing the inner handler hasn't called it yet.
However, `gziphandler` currently calls `WriteHeader(200)` when wrapping up, and because the go stdlib only uses the first call, this breaks things (parent's call becomes void). The same reasoning goes for calling `.Write()`: `gziphandler` should not call .Write() when no .Write() was ever called on itself.
I've updated the logic to never call `WriteHeader()` when `.code` is still 0 (and removed the one-liner `writeHeader` indirection while I was at it), and to make the distinction between `Write()` being called or not by keeping `.buf` to `nil`. This way even a `.Write([]byte{})` will result in the …

Never write to parent ResponseWriter if we were not written to

---

gzip.go
gzip_test.go

In my case with [Up](https://github.com/apex/up) (reverse proxy) the origin may have already compressed, so it would be safe for this middleware to nop. Let me know if you want anything tweaked!

fix handling of responses which are already compressed

---

gzip.go
gzip_test.go

In the stdlib, when we call `Flush` on a response writer, if the status code header was never wrote, it write a 200 status code
As the `WriteHeader` is buffered in `GzipWriter`, if we call Flush in the handler or in a previous middleware, the status code 200 is send even if we have call `WriteHeader` before flushing.

Fix issue on status code when writer flush

---

gzip.go
gzip_test.go

This fixes the bug I noted in https://github.com/NYTimes/gziphandler/pull/58#issuecomment-343036704. In doing so, it reverts 0f67f3f, which was #58, and commits a different fix for that issue.
Where #58 juggled calling `WriteHeader` within `Flush`, this pull request simply makes `Flush` a no-op while the response is buffering, *i.e.* until it reaches the minimum size.
In reverting 0f67f3f, it has the side-effect of reducing the size of the per-request `GzipResponseWriter` struct from 104 bytes to 96 bytes.

Fix Flush breaks response if called while buffering

---

gzip.go
gzip_test.go

GzipResponseWriterWithCloseNotify doesn't implement CloseNotifier, but *GzipResponseWriterWithCloseNotify does.
Fix the tests to really verify with a request that accept gzip.

Need pointer to implement CloseNotifier

---

gzip.go
gzip_test.go

* zero API change; backwards compatible.
* no change in time or space according to all the current benchmarks
Addresses https://github.com/NYTimes/gziphandler/issues/68

Add support for comparing by MIME.

---

gzip.go
gzip_test.go

Currently there's no way to generate a HEAD response with the correct
headers as the GET unless you set the minSize as 0, but then gzip headers
will be written in Close. Instead, allow a Write(nil) that will set the
correct headers based on the Content-Length/Content-Type headers and only
initialize a writer if there is a non-zero-length Write. If the
Content-Length cannot be determined, you cannot generate the response
because it cannot know if minSize would've been met.
Fixes #70

Check Content-Length against minSize and passthrough writes if no gzip

---

gzip.go
gzip_test.go

@jprobinson Small change that somehow I missed in #71. Apparently in specific scenarios WriteHeader can be called twice which doesn't actually break anything but causes `http: multiple response.WriteHeader calls` logs. Setting the code to 0 after we call WriteHeader prevents Close from triggering the WriteHeader. I added a test as well to verify.

Fixed double WriteHeader calls caused by #71

---

gzip.go

Using this library in one of my projects, I came to realise our API for Server-Sent Events stopped working when the request included an `Accept-Encoding: gzip` header.
Investigating on the gziphandler code I found out that, even though I added only `application/json` as the list of supported content types to be GZIPped, 2 little issues led to SSE stop working:
- The `handleContentType` function wasn't being checked until the response actually reached the specified `minSize` (which I left to the default). The `Content-Type` was already being set to an unsupported content type (`text/event-stream`) so we didn't need to wait all the first 1400 bytes before starting the plain response. Fixed this on the first commit.
- The `Flush` func was not flushing the underlying `ResponseWriter` when we …

Start plain response as soon as certain

---

README.md
go.mod
go.sum
gzip.go

Ensure org name in the import path is always NYTimes
